### ISSUE TITLE
Instrument model for DC1

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#20]
Related to https://github.com/CMB-S4/s4mapbasedsims/issues/19, we need the latest instrument parameters

@smsimon can you please point me to the beam widths I should use for DC1?
We don't need bandpasses as we are running only CMB.

**Comment by jdborrill** [comment]
Note that the SAT MF and LF designs may still change.

Presumably this will change the beam widths, Sara?

Julian

**Comment by smsimon** [comment]
The beam FWHMs are in the frozen spreadsheet here (should be the same as the design tool):
https://docs.google.com/spreadsheets/d/10MCZvKLw4oyB_6nX5WBdkhiGXp6l7FiImWTRjufFU94/edit?usp=sharing

And yes, they are reworking some of the SAT optics for the pixel size studies (SAT MF/LF), so depending on the outcome of those, the beam FWHMs may change some. (Though we haven't heard anything on that yet)

**Comment by zonca** [comment]
thanks @smsimon, I doublechecked them, they are all the same.

Should I wait or can I run the simulations of the input sky with the current beam widths?

**Comment by smsimon** [comment]
If you have to run them all at once, I would think that we'd run them and then re-run if there are changes to SAT MF/LF. But if you can just run specific ones, I'd run all but the SAT MF/LF.

**Comment by jdborrill** [comment]
Since we don't know if the SAT MF/LF will be available in time, and the
computational cost is negligible, I'd suggest running them all now and
re-running just the SAT MF and/or LF if needed.

Julian

**Comment by smsimon** [comment]
That sounds good to me

**Comment by smsimon** [comment]
For this run, we will keep the SAT LF layout the same as it was, so the beam should be the same. The SAT MF optics designs have changed, but the feedback from the SAT group is that the beam size depends on the edge tapers of the horns. Potential changes they are considering would only change the beam <5%, and detailed optics simulations would be needed to get an exact number. Since the edge tapers are very similar to early designs, they think the FWHM should remain the same for the SAT MF sims.
