### ISSUE TITLE
DC-0 Validation spectra: Synchrotron

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#29]
@giuspugl the other issue I noted, also in https://github.com/simonsobs/map_based_simulations/issues/44#issuecomment-1481586936 is spikes at high-ell in the Synchrotron maps.

![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/1e9b7d4f-0f44-4e8b-b5f0-a5ceebae5663)
![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/388904d6-55b3-4126-b9ae-74aaa1d8e5e8)
![image](https://github.com/CMB-S4/s4mapbasedsims/assets/383090/9349ecfe-f5a3-4c5d-8ffa-ee41b57a3406)

Should check if they are still there when masking.

**Comment by giuspugl** [comment]
hello, not sure what it might cause this honestly . 
those are spikes at ell~3000 with overtunes at integer multipoles of  ell~3000, i.e. 6000 and 9000.

**Comment by zonca** [comment]
@giuspugl I agree, it also simplifies the dust models. Alternatively what if we apply just a tiny bit of smoothing to the real data to smooth out pixel effects? Is it confirmed that the problem is `ud_grade`?

It would be good to have feedback from @seclark and @brandonshensley.

**Comment by giuspugl** [comment]
> Alternatively what if we apply just a tiny bit of smoothing to the real data to smooth out pixel effects?

well, this seems to me a bit as an epicycle approach. We need to convolve the template by a beam of ~5' to avoid that spectra explodes at ell=2000. Although it seems totally  feasible , it 's true that few users would look at the ell=2000 power spectrum of Gal. plane...

**Comment by seclark** [comment]
Recording that we discussed this on the PanEx call today and plan to not make the change for now, but to note it as a caveat to the models in the current paper. We do not expect that this will affect typical use cases since these models are not designed to reproduce the power spectrum of the Galactic center, and we will address this in the future as we update our treatment of small scale structure in bright regions anyway.

**Comment by zonca** [comment]
documented in PySM, see the linked issues.
